# Generated by Django 4.2.18 on 2026-01-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], default='family', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
