# Generated by Django 4.2.18 on 2026-01-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0002_alter_hotel_available_rooms_alter_hotel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=20)),
                ('price_per_night', models.PositiveIntegerField()),
                ('total_rooms', models.PositiveIntegerField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='onehub_app.hotel')),
            ],
        ),
    ]
