# Generated by Django 4.2.18 on 2026-01-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0004_remove_hotel_available_rooms_remove_hotel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('family', 'Family'), ('bachelor', 'Bachelor'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], default='family', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
