# Generated by manual creation to add hotelname field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0008_foodadmin_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
