# Generated by Django 4.2.18 on 2026-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0015_alter_product_category_ecommerceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='ecommerceorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ecommerceorder',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
