# Generated by Django 4.2.18 on 2026-01-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0016_ecommerceorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
