# Generated by Django 4.2.18 on 2026-01-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0018_hotelrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
