# Generated by Django 6.0 on 2026-01-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0019_user_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='FoodAdmin',
        ),
    ]
