# Generated by Django 6.0 on 2026-02-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0020_delete_dish_delete_foodadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tourist Category',
                'verbose_name_plural': 'Tourist Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('short_description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField()),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_fees', models.CharField(blank=True, max_length=200, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='tourist_places/featured/')),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags (e.g., nature, family, budget, luxury)', null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourist_places', to='onehub_app.touristcategory')),
            ],
            options={
                'verbose_name': 'Tourist Place',
                'verbose_name_plural': 'Tourist Places',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NearbyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel'), ('package', 'Tourist Package'), ('transport', 'Transportation'), ('guide', 'Local Guide')], max_length=20)),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('website_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tourist_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_services', to='onehub_app.touristplace')),
            ],
            options={
                'verbose_name': 'Nearby Service',
                'verbose_name_plural': 'Nearby Services',
                'ordering': ['service_type', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_places/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tourist_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='onehub_app.touristplace')),
            ],
            options={
                'verbose_name': 'Tourist Place Image',
                'verbose_name_plural': 'Tourist Place Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
