# Generated by Django 6.0 on 2026-02-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0021_touristcategory_touristplace_nearbyservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristplace',
            name='category',
        ),
        migrations.RemoveField(
            model_name='touristplaceimage',
            name='tourist_place',
        ),
        migrations.DeleteModel(
            name='NearbyService',
        ),
        migrations.DeleteModel(
            name='TouristCategory',
        ),
        migrations.DeleteModel(
            name='TouristPlace',
        ),
        migrations.DeleteModel(
            name='TouristPlaceImage',
        ),
    ]
