# Generated by Django 6.0 on 2026-02-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onehub_app', '0022_remove_touristplace_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_time', models.CharField(blank=True, help_text='e.g., 9:00 AM - 6:00 PM', max_length=100, null=True)),
                ('location_link', models.URLField(blank=True, help_text='Google Maps URL or location link', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tourist Place',
                'verbose_name_plural': 'Tourist Places',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_places/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tourist_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='onehub_app.touristplace')),
            ],
            options={
                'verbose_name': 'Tourist Place Image',
                'verbose_name_plural': 'Tourist Place Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
